# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details

---
fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: v9.0.0
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
      ref: v7.0.0
    systemd:
      repo: https://github.com/voxpupuli/puppet-systemd.git
      ref: v8.1.0
  symlinks:
    etcd: "#{source_dir}"
