# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details

---
fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
    systemd:
      repo: https://github.com/voxpupuli/puppet-systemd.git
  symlinks:
    etcd: "#{source_dir}"
