---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el8
      - el9
      - debian-11
      - ubuntu-2004
    puppet:
      - puppet7
      - puppet8
.travis.yml:
  delete: true
Rakefile:
  changelog_user: tailored-automation
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
